name: Type Coverage

on:
  pull_request:

jobs:
  phpstan:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Install Composer Dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run Static Analysis
        run: vendor/bin/phpstan analyse --memory-limit=2G
